name: local
variables:
- name: baseUrl
  value: http://127.0.0.1:8787
- secret: true
  name: token
- name: note
  value: ''
- name: base
  value: ''
- name: view
  value: ''
- name: folder
  value: ''
- name: scratchFolder
  value: Bruno
- name: cursor
  value: ''
